import {Component, OnInit} from '@angular/core';
import {Product} from "../../models/product";
import {ProductService} from "../services/product.service";
import {CartService} from "../services/cart.service";
import {CartItem} from "../../models/cart-item";

@Component({
  selector: 'app-cart-product-list',
  templateUrl: './cart-product-list.component.html',
  styleUrl: './cart-product-list.component.css'
})
export class CartProductListComponent implements OnInit {
  products: Product[] = [];

  constructor(private productService: ProductService, private cartService: CartService) { }

  ngOnInit(): void {
    this.productService.getAllProducts().subscribe(products => {
      this.products = products;
    });
  }

  addToCart(product: Product): void {
    const cartItem: CartItem = {
      id: 0, // the id will be generated by the backend
      product: product,
      quantity: 1
    };

    this.cartService.addCartItem(cartItem).subscribe(() => {
      alert('Produit ajouté au panier');
    });
  }
}
